#!/bin/bash

# disable selinux and setenforce 0
# yum --enablerepo=updates-testing install nodejs npm
# yum install python-netaddr

# Networking
# HOST_IP=192.168.122.8

# Passwords
ADMIN_PASSWORD=password
MYSQL_PASSWORD=$ADMIN_PASSWORD
RABBIT_PASSWORD=$ADMIN_PASSWORD
SERVICE_PASSWORD=$ADMIN_PASSWORD
SERVICE_TOKEN=$ADMIN_PASSWORD

# Directories
DEST=$HOME/stack
SCREEN_LOGDIR=$DEST/logs/screen

# Create $DEST if it doesn't exist.
if [ ! -e $DEST ]
then
    mkdir -p $DEST
fi

# stack.sh Logging
LOGFILE=$HOME/stack.sh.log
LOGDAYS=14
LOG_COLOR=True
VERBOSE=False

# qpid is the default for Fedora
disable_service rabbit
enable_service qpid

# Enable swift
# ENABLED_SERVICES+=,swift
# SWIFT_HASH=66a3d6b56c1f479c8b4e70ab5c2000f5
# SWIFT_REPLICAS=1
# SWIFT_DATA_DIR=$DEST/data

# Keystone SQL Service Catalog
# KEYSTONE_CATALOG_BACKEND=sql

# Cinder Volumes
# VOLUME_GROUP="stack-volumes"
# VOLUME_NAME_PREFIX="volume-"
# VOLUME_BACKING_FILE_SIZE=5130M

# API Rate limit
API_RATE_LIMIT=False

IMAGE_URLS=http://launchpad.net/cirros/trunk/0.3.0/+download/cirros-0.3.0-x86_64-uec.tar.gz,http://berrange.fedorapeople.org/images/2012-11-15/f17-x86_64-openstack-sda.qcow2
